model = dict(
    backbone=dict(
        type='HRNet',
        extra=dict(
            stage1=dict(
                num_modules=1,
                num_branches=1,
                block='BOTTLENECK',
                num_blocks=(4, ),
                num_channels=(64, )),
            stage2=dict(
                num_modules=1,
                num_branches=2,
                block='BASIC',
                num_blocks=(4, 4),
                num_channels=(40, 80)),
            stage3=dict(
                num_modules=4,
                num_branches=3,
                block='BASIC',
                num_blocks=(4, 4, 4),
                num_channels=(40, 80, 160)),
            stage4=dict(
                num_modules=3,
                num_branches=4,
                block='BASIC',
                num_blocks=(4, 4, 4, 4),
                num_channels=(40, 80, 160, 320))),
        init_cfg=dict(
            type='Pretrained', checkpoint='open-mmlab://msra/hrnetv2_w40')),
    neck_det=dict(
        type='HRFPN',
        in_channels=[40, 80, 160, 320],
        pooling_type='MAX',
        out_channels=256,
        stride=2,
        num_outs=5),
    neck_rel=dict(
        type='HRFPN',
        in_channels=[48, 96, 192, 384],
        pooling_type='MAX',
        out_channels=256,
        stride=2,
        num_outs=5))
